name: Code checks
on:
  push:
    branches: main
  pull_request:
    branches: main
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1

      - uses: actions/setup-go@v5

      - name: Run Go
        run: make run-go

      - name: Setup CMake
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Run C++
        run: make run-cpp

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Run Python
        run: make run-python

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run TypeScript
        run: make run-typescript
