name: Code checks
on:
  push:
    branches: main
  pull_request:
    branches: main
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker
        run: docker build -t devcontainer:latest -f .devcontainer/Dockerfile .

      - name: Execute make run-python in Container
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace devcontainer:latest /bin/bash -c "make run-python"

      - name: Execute make run-cpp in Container
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace devcontainer:latest /bin/bash -c "make run-cpp"

      - name: Execute make run-go in Container
        run: docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace devcontainer:latest /bin/bash -c "make run-go"
